magento/magento2-login-as-customer

etc/frontend/sections.xml

Move commits to new PR.
1. magento/magento2-login-as-customer#59: Customer data not invalidated private content after logged in
1. Check issue above

login-as-customer/issues/59: Customer data not invalidated private content after logged in

---

Model/Login.php

login-as-customer/issues/61: Active Quotes Duplicate

---

Controller/Adminhtml/Login/Login.php

login-as-customer/issues/62: Create seperate method for getting store id

---

app/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Login.php

1. None
1. Create Customer
2. Open Customer edit page on backend.
3. Press "Login As Customer" button.

Fatal error on Login As Customer hotfix.

---

app/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Grid.php
app/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Index.php
app/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Login.php
app/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Manual.php
app/code/Magento/LoginAsCustomer/Controller/Login/Index.php
app/code/Magento/LoginAsCustomer/Controller/Login/Proceed.php

1. All controller actions now return the ResultInterface implementation.
2. Every action controller now implement one of \Magento\Framework\App\Action\Http*ActionInterface
3. Removed strrev
4. For ajax call now use $request->isXmlHttpRequest() instead of additional parameters
5. Added type hinting for return value
6. Added a short useful description for docblocks (shortly describe the responsibility of controller action)
https://github.com/magento/magento2-login-as-customer/issues/10#Controllers refactoring
https://github.com/magento/magento2-login-as-customer/issues/13#[BUG] TypeError: strrev() expects parameter 1 to be string, object given
- [+] Pull request has a meaningful description of its purpose
- [+] All commits are accompanied by meaningful commit messages

Login As Customer Controllers refactoring

---

app/code/Magento/LoginAsCustomer/Plugin/AdminAddCommentOnOrderPlacementPlugin.php
app/code/Magento/LoginAsCustomer/Plugin/FrontAddCommentOnOrderPlacementPlugin.php
app/code/Magento/LoginAsCustomer/etc/adminhtml/di.xml
app/code/Magento/LoginAsCustomer/etc/webapi_rest/di.xml

1. https://github.com/magento/magento2-login-as-customer/issues/28: Admin order noted in Order Comments.
1. See the issue.

magento2-login-as-customer/issues/28: Admin order noted in Order Comments.

---

app/code/Magento/LoginAsCustomer/etc/acl.xml

This PR will fix the ACL title as per UX Design
1. magento/magento2-login-as-customer#55: Need to update/change titles for ACL resource tree related to Login as Customer

#55 : Need to update/change titles for ACL resource tree related to Login as Customer

---

app/code/Magento/LoginAsCustomer/view/frontend/web/js/login.js

Fix the issue that Login as Customer banner not showing with latest comments
More information here https://github.com/magento/magento2-login-as-customer/issues/17#issuecomment-617119850
1. magento/magento2-login-as-customer#17:Notification banner on storefront [bug: The banner is not showing]
1. Login to the admin panel
2. Go to customers > select customer (go to customer edit page) > press "Login As Customer" button
3. You will need to see the https://prnt.sc/s3rezg
- [+] Pull request has a meaningful description of its purpose
- [+] All commits are accompanied by meaningful commit messages
- [-] All new or changed code is covered with unit/integration tests (if applicable)
- [-] All automated tests passed successfully (all builds are green)

17 Notification banner on storefront [fixed: The banner is not showing]

---

app/code/Magento/LoginAsCustomer/Controller/Login/Proceed.php

This PR will fix the issue with missing title after Login as Customer from admin
1. magento/magento2-login-as-customer#73: Page title is empty when admin login as customer
1. Go to Customers->All Customers
2. Click Edit on existing customer
3. Click on Login as Customer button

#73 :- Page title is empty when admin login as customer

---

app/code/Magento/LoginAsCustomer/Cron/DeleteExpiredAuthenticationData.php
app/code/Magento/LoginAsCustomer/Model/AuthenticateCustomer.php
app/code/Magento/LoginAsCustomer/Model/AuthenticationData.php
app/code/Magento/LoginAsCustomerLog/Model/Login.php
app/code/Magento/LoginAsCustomerLog/Model/ResourceModel/Login.php
app/code/Magento/LoginAsCustomerLog/Model/ResourceModel/Login/Collection.php
app/code/Magento/LoginAsCustomerLog/Model/ResourceModel/Login/Grid/Collection.php
app/code/Magento/LoginAsCustomerPageCache/Plugin/PageCache/Model/Config/DisablePageCacheIfNeededPlugin.php
app/code/Magento/LoginAsCustomerSales/Plugin/AdminAddCommentOnOrderPlacementPlugin.php
app/code/Magento/LoginAsCustomerSales/Plugin/AuthenticateCustomerPlugin.php
app/code/Magento/LoginAsCustomerSales/Plugin/FrontAddCommentOnOrderPlacementPlugin.php
app/code/Magento/LoginAsCustomerSales/composer.json
app/code/Magento/LoginAsCustomerUi/Controller/Adminhtml/Login/Login.php
app/code/Magento/LoginAsCustomerUi/Model/Config/Source/StoreViewLogin.php
app/code/Magento/LoginAsCustomerUi/ViewModel/Configuration.php
app/code/Magento/LoginAsCustomerUi/view/frontend/templates/html/notices.phtml
app/code/Magento/LoginAsCustomerUi/view/frontend/templates/html/notices/logout-link.phtml
app/code/Magento/LoginAsCustomerUi/view/frontend/templates/login.phtml
app/code/Magento/LoginAsCustomerUi/view/frontend/web/css/source/_module.less
dev/tests/static/testsuite/Magento/Test/Integrity/Magento/Framework/Api/_files/ExtensibleInterfacesTest/blacklist_ce.txt

magento2-login-as-customer/issues/104: Global refactoring

---

app/code/Magento/LoginAsCustomer/composer.json
app/code/Magento/LoginAsCustomer/etc/config.xml
app/code/Magento/LoginAsCustomerApi/Api/ConfigInterface.php
app/code/Magento/LoginAsCustomerLog/composer.json
app/code/Magento/LoginAsCustomerSales/Plugin/AuthenticateCustomerPlugin.php
app/code/Magento/LoginAsCustomerSales/composer.json
app/code/Magento/LoginAsCustomerUi/Controller/Adminhtml/Login/Login.php
app/code/Magento/LoginAsCustomerUi/ViewModel/Configuration.php
app/code/Magento/LoginAsCustomerUi/composer.json
app/code/Magento/LoginAsCustomerUi/etc/adminhtml/system.xml
app/code/Magento/LoginAsCustomerUi/view/frontend/templates/html/notices.phtml
app/code/Magento/LoginAsCustomerUi/view/frontend/web/css/source/_module.less
composer.lock

Builds stabilization and bug fix
1. https://github.com/magento/magento2-login-as-customer/issues/90
1. ...
2. ...

Tests stabilization.

---

app/code/Magento/LoginAsCustomerPageCache/etc/adminhtml/system.xml
app/code/Magento/LoginAsCustomerUi/etc/adminhtml/system.xml

Make LoginAsCustomer Store config options global.
1. https://github.com/magento/magento2-login-as-customer/issues/16 All System Configuration settings should be on Global level
Described in the related issue
- [+] Pull request has a meaningful description of its purpose
- [+] All commits are accompanied by meaningful commit messages

All System Configuration settings should be on Global level

---

app/code/Magento/LoginAsCustomer/etc/db_schema.xml
app/code/Magento/LoginAsCustomerApi/Api/ConfigInterface.php
app/code/Magento/LoginAsCustomerLog/Controller/Adminhtml/Log/Index.php
app/code/Magento/LoginAsCustomerLog/README.md
app/code/Magento/LoginAsCustomerLog/etc/adminhtml/menu.xml
app/code/Magento/LoginAsCustomerUi/Controller/Adminhtml/Login/Login.php
app/code/Magento/LoginAsCustomerUi/Controller/Login/Index.php
app/code/Magento/LoginAsCustomerUi/Plugin/Button/ToolbarPlugin.php
app/code/Magento/LoginAsCustomerUi/Ui/Customer/Component/Control/LoginAsCustomerButton.php
app/code/Magento/LoginAsCustomerUi/Ui/Store/Component/Control/LoginAsCustomerButton.php

1. https://github.com/magento/magento2-login-as-customer/issues/95: Incorrect text value. In all places should be used "Login as Customer" instead of "Login As Customer"
1. ...
2. ...

magento2-login-as-customer/issues/95:Incorrect text value. In all places should be used "Login as Customer" instead of "Login As Customer"

---

app/code/Magento/LoginAsCustomerLog/Controller/Adminhtml/Log/Index.php
app/code/Magento/LoginAsCustomerLog/etc/adminhtml/menu.xml

1. https://github.com/magento/magento2-login-as-customer/issues/136: Login as Customer Log is available when Login as Customer is disabled.
1. See https://github.com/magento/magento2-login-as-customer/issues/136

magento2-login-as-customer/issues/136: Login as Customer Log is available when Login as Customer is disabled.

---

app/code/Magento/LoginAsCustomerUi/Controller/Adminhtml/Login/Login.php

1. https://github.com/magento/magento2-login-as-customer/issues/134:  Login as Customer not working if store view code is added to url.
1. ...
2. ...

magento2-login-as-customer/issues/134: Login as Customer not working if store view code is added to url.

---

app/code/Magento/LoginAsCustomerUi/view/frontend/templates/login.phtml
app/code/Magento/LoginAsCustomerUi/view/frontend/web/js/login.js

1. https://github.com/magento/magento2-login-as-customer/issues/145: Spinner/Loader should appear before page content.
1. See https://github.com/magento/magento2-login-as-customer/issues/145.

magento2-login-as-customer/issues/145: Spinner/Loader should appear before page content.

---

app/code/Magento/LoginAsCustomerUi/view/adminhtml/web/js/confirmation-popup.js

1. https://github.com/magento/magento2-login-as-customer/issues/137: Login as Customer incorrect popup message.
1. See https://github.com/magento/magento2-login-as-customer/issues/137

magento2-login-as-customer/issues/137: Login as Customer incorrect popup message.

---

app/code/Magento/LoginAsCustomer/Plugin/AdminLogoutPlugin.php
app/code/Magento/LoginAsCustomer/etc/config.xml

1. Fixes magento/magento2-login-as-customer#144: "Login as Customer" functionality should be enabled by default.
1. See magento/magento2-login-as-customer#144: "Login as Customer" functionality should be enabled by default.

magento/magento2-login-as-customer#144: "Login as Customer" functionality should be enabled by default.

---

app/code/Magento/LoginAsCustomerQuote/Plugin/LoginAsCustomerApi/ProcessShoppingCartPlugin.php

Banner is not shown on the page if customer is not sign out from account 
https://github.com/magento/magento2-login-as-customer/pull/162
1. Fixes https://github.com/magento/magento2-login-as-customer/issues/159
Can be found in the ticket https://github.com/magento/magento2-login-as-customer/issues/159
I have moved $quote->setCustomerIsGuest(0); before as originaly it was added there
https://github.com/magefan/module-login-as-customer/commit/ce089ba5f738eca21918f080b509f3a0e7a2311f but trying to fix some Magento core issue on old version for some client (no-related  to the module, but occurred when logged as customer) it was moved after https://github.com/magefan/module-login-as-customer/commit/17a3da43ec040508064a029a3036776f77ccaaeb#diff-6a843246b861bf267de5c2f5189c7a18
- [+] Pull …

Magento2 login as customer/issues/159

---

app/code/Magento/LoginAsCustomerFrontendUi/view/frontend/web/js/view/loginAsCustomer.js

1. Fixes magento/magento2-login-as-customer#156: Banner disappear when admin edit customer data from Account Information tab.
1. See the issue.

magento/magento2-login-as-customer#156: Banner disappear when admin edit customer data from Account Information tab.

---

app/code/Magento/LoginAsCustomerFrontendUi/view/frontend/layout/loginascustomer_login_index.xml

1. Fixes magento/magento2-login-as-customer#158: Enable Page Cache - Admin is not logged in as customer because was redirected to the "Sign In" page.
1. See magento/magento2-login-as-customer#158: Enable Page Cache - Admin is not logged in as customer because was redirected to the "Sign In" page.

magento/magento2-login-as-customer#158: Enable Page Cache - Admin is not logged in as customer because was redirected to the "Sign In" page.

---

app/code/Magento/LoginAsCustomerFrontendUi/Plugin/InvalidateExpiredSessionPlugin.php

1. Fixes magento/magento2-login-as-customer#186: [CE] Admin cannot login as customer in two different customers account
1. See magento/magento2-login-as-customer#186: [CE] Admin cannot login as customer in two different customers account

magento/magento2-login-as-customer#186: [CE] Admin cannot login as customer in two different customers account

---

app/code/Magento/LoginAsCustomerSales/etc/frontend/di.xml

1. Fixes magento/magento2-login-as-customer#190: No order comments are created when admin is logged in as customer and place order with Multiple Addresses.
1. See magento/magento2-login-as-customer#190: No order comments are created when admin is logged in as customer and place order with Multiple Addresses.

magento/magento2-login-as-customer#190: No order comments are created when admin is logged in as customer and place order with Multiple Addresses.
